# Generated by Django 3.1 on 2021-01-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.education'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.ManyToManyField(default=1, to='auth_app.Language'),
        ),
    ]
